// Demo projects. All of them use real packages and real versions; the npm
// lockfile was generated by npm itself (`npm install --package-lock-only
// --ignore-scripts`), not written by hand. Files are loaded lazily.

const loaders = import.meta.glob('./samples/**/*', { query: '?raw', import: 'default' })

export const SAMPLES = [
  {
    id: 'express-shop',
    title: 'Tienda Express (npm)',
    format: 'package-lock.json',
    blurb: 'Lockfile real con 178 paquetes. Muestra dependencias transitivas, rutas y prod frente a dev.',
    expect: 'FAIL',
  },
  {
    id: 'flask-api',
    title: 'API Flask de 2021 (pip)',
    format: 'requirements.txt',
    blurb: 'Versiones fijadas y una sin fijar: la herramienta dice qué no pudo comprobar.',
    expect: 'FAIL',
  },
  {
    id: 'java-sbom',
    title: 'Servicio Java (SBOM)',
    format: 'CycloneDX',
    blurb: 'Log4Shell y Spring4Shell: vulnerabilidades en CISA KEV que se convierten en P0.',
    expect: 'FAIL',
  },
  {
    id: 'fastapi-clean',
    title: 'Servicio al día (pip)',
    format: 'requirements.txt',
    blurb: 'Dependencias recientes: un PASS sólo cuando todo se pudo comprobar.',
    expect: 'PASS',
  },
  {
    id: 'broken-lock',
    title: 'Lockfile con conflicto de merge',
    format: 'package-lock.json',
    blurb: 'Archivo corrupto: el resultado es INCOMPLETE, nunca un falso "sin vulnerabilidades".',
    expect: 'INCOMPLETE',
  },
]

/** -> Promise<[{path, content}]> */
export async function loadSample(id) {
  const prefix = `./samples/${id}/`
  const entries = Object.entries(loaders).filter(([path]) => path.startsWith(prefix))
  const files = await Promise.all(
    entries.map(async ([path, load]) => ({ path: path.slice(prefix.length), content: await load() })),
  )
  return files.sort((a, b) => (a.path < b.path ? -1 : 1))
}
